server:
  port: 80
spring:
  application:
    name: back-end
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/stu_pallet
    username: root
    password: 123456
  session:
    timeout: 86400
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false

